### ISSUE TITLE
Wrong total-degree basis computed by `basis_anisotropic_total_order`

### ISSUE THREAD

**Issue by luethen** [CU-UQ/BASE_PC#1]
Dear developers, thank you very much for making your software available!

When computing a total order basis (not anisotropic) with the function `basis_anisotropic_total_order`, in certain cases some elements are missing from the basis. This seems to be a numerical issue of the comparison in line 57. The bug disappears when replacing line 57 with `if(sum(basis_array_prop./m_ord) <= 1.0 + 1e-12)`.

Code to reproduce the bug: 
```
% Bug in basis_anisotropic_total_order?
fprintf('Testing basis_anisotropic_total_order...\n')
basis_opt.dim = 4;
fprintf('dim = %d\n', basis_opt.dim);
total_degree = 10;
fprintf('total_degree = %d\n', total_degree);
basis_opt.ord = total_degree * ones(1, basis_opt.dim);
fprintf('ord = '); fprintf('%d ', basis_opt.ord); fprintf('\n');

basis1 = basis_anisotropic_total_order(basis_opt);

fprintf('Number of elements in basis: %d\n', basis1.n_elems);
fprintf('(dim + total_degree) choose (dim) = %d\n', nchoosek(basis_opt.dim + total_degree, basis_opt.dim));

fprintf('Number of elements is ');
if basis1.n_elems ~= nchoosek(basis_opt.dim + total_degree, basis_opt.dim)
    fprintf('NOT ');
end
fprintf('correct!\n')
```

**Comment by qcxv** [comment]
Thank you @luethen for finding and solving this issue. I have made the change as you requested.
